@startuml "tower_defense_uml"

/' left to right direction '/
/' skinparam linetype ortho '/
/' skinparam linetype polyline '/

class GameManager implements I_UIObserver, I_GameManagerMediator {
    - gameboardManager : I_GameboardManager
    - levelManager : I_LevelManager
    - waveManager : I_WaveManager
    - shopManager : I_ShopManager
    - playerManager : I_PlayerManager
    - systemObserver : I_SystemObserver
    + start()
    + end()
}

class System implements I_SystemObserver {
    - hudManager : I_HudManager
    - soundManager : I_SoundManager
    - logger : List<I_Logger>
    - gameManager : GameManager
}

interface I_Logger {
    + log()
}


class FileLogger implements I_Logger {
}

class ConsoleLogger implements I_Logger {
}

class DatabaseLogger implements I_Logger {
}

' note left of GameManager
'     Orchestre le cycle de vie du jeu en
'     coordonnant les différents gestionnaires
'     nécessaires au fonctionnement du TowerDefense.
' end note

abstract class I_GameboardManager  {
    - mediator : I_GameManagerMediator
    + addEnemy(enemie : I_Enemie)
    + addTower(tower : I_Tower)
}

abstract class I_LevelManager  {
    - mediator : I_GameManagerMediator
    + loadLevel()
    + restartLevel()
}

abstract class I_WaveManager  {
    - mediator : I_GameManagerMediator
    + startWave()
}

abstract class I_ShopManager   {
    - mediator : I_GameManagerMediator
    + buyItem()
}

abstract class I_PlayerManager  {
    - mediator : I_GameManagerMediator
    + getLifePoint()
    + getMoney()
}

abstract class I_HudManager {
    - uiObserver : I_UIObserver
    + showLevel(int level)
    + showTowerShop(towersImages : List<TowersImage>)
    + showMenu()
    + showError()
    + sendUIEvent()
}

interface I_SoundManager {
    + increase()
    + decrease()
    + mute()
}

interface I_SystemObserver {
    + onEvent()
}

interface I_UIObserver {
    + onEventFromUI()
}

interface I_GameManagerMediator {
    + notifyGameManager()
}

GameManager o-- I_GameboardManager
GameManager o-- I_LevelManager
GameManager o-- I_WaveManager
GameManager o-- I_ShopManager
GameManager o-- I_PlayerManager
GameManager o-- I_SystemObserver

System *-- I_HudManager
System *-- I_SoundManager
System *-- I_Logger
System *-- GameManager

I_HudManager --> I_UIObserver


I_GameManagerMediator <-- I_GameboardManager
I_GameManagerMediator <-- I_LevelManager
I_GameManagerMediator <-- I_PlayerManager
I_GameManagerMediator <-- I_WaveManager
I_GameManagerMediator <-- I_ShopManager


class Tower {

}

class Hud {

}

class Gameboard {

}

class Wave {

}

class Shop {

}

class Player {

}
@enduml